<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-09T18:23:07 IST" name="Default suite" finished-at="2021-06-09T18:25:10 IST" duration-ms="122579">
    <groups>
    </groups>
    <test started-at="2021-06-09T18:23:07 IST" name="Default test" finished-at="2021-06-09T18:25:10 IST" duration-ms="122579">
      <class name="TestCases.TU10_TC_01">
        <test-method is-config="true" signature="report()[pri:0, instance:TestCases.TU10_TC_01@778d1062]" started-at="2021-06-09T18:23:07 IST" name="report" finished-at="2021-06-09T18:23:07 IST" duration-ms="237" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- report -->
        <test-method is-config="true" signature="pre()[pri:0, instance:TestCases.TU10_TC_01@778d1062]" started-at="2021-06-09T18:23:07 IST" name="pre" finished-at="2021-06-09T18:23:35 IST" duration-ms="27124" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pre -->
        <test-method signature="VerifyErrors()[pri:0, instance:TestCases.TU10_TC_01@778d1062]" started-at="2021-06-09T18:23:35 IST" name="VerifyErrors" finished-at="2021-06-09T18:25:09 IST" duration-ms="94635" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please fill in your First name] but found [[[ChromeDriver: chrome on WINDOWS (833cf898a8a4e94f353d97c168d280bc)] -> xpath: //*[text()=' Please fill in your First name']]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please fill in your First name] but found [[[ChromeDriver: chrome on WINDOWS (833cf898a8a4e94f353d97c168d280bc)] -> xpath: //*[text()=' Please fill in your First name']]]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at POM.POM_Booking_errors.VerifyFirstNameError(POM_Booking_errors.java:19)
at TestCases.TU10_TC_01.VerifyErrors(TU10_TC_01.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyErrors -->
        <test-method is-config="true" signature="peerdown()[pri:0, instance:TestCases.TU10_TC_01@778d1062]" started-at="2021-06-09T18:25:09 IST" name="peerdown" finished-at="2021-06-09T18:25:10 IST" duration-ms="536" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- peerdown -->
      </class> <!-- TestCases.TU10_TC_01 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
